#6328: Demo-Page Improvements
renuo/renuo-upload-demo pull request #13
Opened 2016-09-19 13:41 UTC by pascalandermatt

+/- Text jump slower
+/- Delay after upload a picture
+/- Make fonts consistent
+ Added footer text

2016-09-19 14:53 UTC, schmijos commented on src/index.html
> +              uploading files where not satisfying, we built a upload
Typo: where --> were

2016-09-19 14:56 UTC, schmijos requested changes

2016-09-20 06:44 UTC, pascalandermatt commented on src/index.html
> +              uploading files where not satisfying, we built a upload
Habe es aus dem ReadMe kopiert
https://github.com/renuo/renuo-upload-doc/blob/master/README.md
Habe es ebenfalls dort verbessert -> Pull Request

2016-09-20 08:32 UTC, schmijos approved these changes

2016-09-20 08:33 UTC, merged